(base) PS D:\Fuentes\Bnamericas\covid19_ultrasound\pocovidnet>  python scripts/train_covid19.py --data_dir ../data/cross_validation/ --fold 4 --epochs 30 -m data/V1/30-epocas
2021-03-29 17:39:36.157936: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Model parameters: {'data_dir': '../data/cross_validation/', 'model_dir': 'data/V1/30-epocas', 'fold': 4, 'learning_rate': 0.0001, 'epochs': 30, 'batch_size': 16, 'trainable_base_layers': 1, 'img_width': 224, 'img_height': 224, 'model_id': 'vgg_base', 'log_softmax': False, 'model_name': 'test', 'hidden_size': 64}
Loading images...
selected fold: 4

Number of training samples: 1587
Number of testing samples: 562
Class mappings are: ['covid' 'pneumonia' 'regular']
2021-03-29 17:39:52.539642: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-29 17:39:52.541575: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-29 17:39:53.500653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2021-03-29 17:39:53.500896: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-29 17:39:53.524283: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-29 17:39:53.524459: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-29 17:39:53.533001: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-29 17:39:53.536660: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-29 17:39:53.546372: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-29 17:39:53.554111: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-29 17:39:53.556385: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-29 17:39:53.556683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-29 17:39:53.558134: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-29 17:39:53.558985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2021-03-29 17:39:53.559249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-29 17:39:53.560235: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-29 17:39:53.565195: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-29 17:39:53.568583: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-29 17:39:53.569192: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-29 17:39:53.569805: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-29 17:39:53.570486: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-29 17:39:53.571125: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-29 17:39:53.571871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-29 17:39:54.405173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-29 17:39:54.405356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-03-29 17:39:54.408077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-03-29 17:39:54.412557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2987 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-03-29 17:39:54.414145: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Compiling model...
Model has 14747971 parameters
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0
_________________________________________________________________
average_pooling2d (AveragePo (None, 1, 1, 512)         0
_________________________________________________________________
flatten (Flatten)            (None, 512)               0
_________________________________________________________________
dense (Dense)                (None, 64)                32832
_________________________________________________________________
batch_normalization (BatchNo (None, 64)                256
_________________________________________________________________
re_lu (ReLU)                 (None, 64)                0
_________________________________________________________________
dropout (Dropout)            (None, 64)                0
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 195
=================================================================
Total params: 14,747,971
Trainable params: 2,392,963
Non-trainable params: 12,355,008
_________________________________________________________________
Model summary None
Starting training model...
d:\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '
2021-03-29 17:39:56.189277: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
Epoch 1/30
2021-03-29 17:39:58.289483: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-29 17:39:58.804549: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-29 17:39:59.044281: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-29 17:40:00.523939: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-03-29 17:40:00.626079: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-03-29 17:40:01.918955: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
99/99 [==============================] - ETA: 0s - loss: 0.9557 - accuracy: 0.56822021-03-29 17:40:41.692766: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
99/99 [==============================] - 60s 490ms/step - loss: 0.9540 - accuracy: 0.5692 - val_loss: 0.6988 - val_accuracy: 0.6530

Epoch 00001: val_accuracy improved from -inf to 0.65302, saving model to data/V1/30-epocas\test\fold_4\best_weights
2021-03-29 17:40:58.206089: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-03-29 17:41:05.160121: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-29 17:41:05.160490: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.04GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-29 17:41:05.264624: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.74GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-29 17:41:08.790175: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-29 17:41:22.447481: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.60GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Balanced accuracy is: {'val_balanced': 0.3923611111111111}
Epoch 2/30
99/99 [==============================] - 31s 309ms/step - loss: 0.6064 - accuracy: 0.7663
Balanced accuracy is: {'val_balanced': 0.7634099616858238}
Epoch 3/30
99/99 [==============================] - 31s 308ms/step - loss: 0.4715 - accuracy: 0.8069
Balanced accuracy is: {'val_balanced': 0.5689655172413793}
Epoch 4/30
99/99 [==============================] - 31s 311ms/step - loss: 0.4407 - accuracy: 0.8364
Balanced accuracy is: {'val_balanced': 0.8144157088122604}
Epoch 5/30
99/99 [==============================] - 31s 313ms/step - loss: 0.3750 - accuracy: 0.8679
Balanced accuracy is: {'val_balanced': 0.7817289272030652}
Epoch 6/30
99/99 [==============================] - 31s 316ms/step - loss: 0.3855 - accuracy: 0.8696
Balanced accuracy is: {'val_balanced': 0.8332136015325671}
Epoch 7/30
99/99 [==============================] - 31s 316ms/step - loss: 0.3660 - accuracy: 0.8669
Balanced accuracy is: {'val_balanced': 0.7505986590038315}
Epoch 8/30
99/99 [==============================] - 31s 313ms/step - loss: 0.3761 - accuracy: 0.8773
Balanced accuracy is: {'val_balanced': 0.818845785440613}
Epoch 9/30
99/99 [==============================] - 32s 320ms/step - loss: 0.3465 - accuracy: 0.8839
Balanced accuracy is: {'val_balanced': 0.8280651340996169}
Epoch 10/30
99/99 [==============================] - 31s 315ms/step - loss: 0.2926 - accuracy: 0.9131
Balanced accuracy is: {'val_balanced': 0.879435550082102}
Epoch 11/30
99/99 [==============================] - 32s 317ms/step - loss: 0.2651 - accuracy: 0.9107
Balanced accuracy is: {'val_balanced': 0.8208812260536398}
Epoch 12/30
99/99 [==============================] - 32s 320ms/step - loss: 0.2867 - accuracy: 0.9102
Balanced accuracy is: {'val_balanced': 0.8102250957854406}
Epoch 13/30
99/99 [==============================] - 31s 313ms/step - loss: 0.2969 - accuracy: 0.9187
Balanced accuracy is: {'val_balanced': 0.7547892720306514}
Epoch 14/30
99/99 [==============================] - 31s 316ms/step - loss: 0.2261 - accuracy: 0.9140
Balanced accuracy is: {'val_balanced': 0.806154214559387}
Epoch 15/30
99/99 [==============================] - 32s 317ms/step - loss: 0.2387 - accuracy: 0.9213
Balanced accuracy is: {'val_balanced': 0.8212404214559387}
Epoch 16/30
99/99 [==============================] - 31s 310ms/step - loss: 0.2339 - accuracy: 0.9149
Balanced accuracy is: {'val_balanced': 0.6906130268199234}
Epoch 17/30
99/99 [==============================] - 32s 323ms/step - loss: 0.2992 - accuracy: 0.9043
Balanced accuracy is: {'val_balanced': 0.7866379310344828}
Epoch 18/30
99/99 [==============================] - 31s 315ms/step - loss: 0.2603 - accuracy: 0.9183
Balanced accuracy is: {'val_balanced': 0.8251915708812261}
Epoch 19/30
99/99 [==============================] - 32s 325ms/step - loss: 0.2374 - accuracy: 0.9226
Balanced accuracy is: {'val_balanced': 0.8924808429118775}
Epoch 20/30
99/99 [==============================] - 31s 311ms/step - loss: 0.2176 - accuracy: 0.9276
Balanced accuracy is: {'val_balanced': 0.8608716475095785}
Epoch 21/30
99/99 [==============================] - 33s 329ms/step - loss: 0.2083 - accuracy: 0.9393
Balanced accuracy is: {'val_balanced': 0.8826361521620143}
Epoch 22/30
99/99 [==============================] - 32s 324ms/step - loss: 0.1877 - accuracy: 0.9471
Balanced accuracy is: {'val_balanced': 0.8079501915708812}
Epoch 23/30
99/99 [==============================] - 31s 315ms/step - loss: 0.1964 - accuracy: 0.9359
Balanced accuracy is: {'val_balanced': 0.8643438697318008}
Epoch 24/30
99/99 [==============================] - 32s 320ms/step - loss: 0.2059 - accuracy: 0.9303
Balanced accuracy is: {'val_balanced': 0.8016044061302683}
Epoch 25/30
99/99 [==============================] - 32s 319ms/step - loss: 0.1965 - accuracy: 0.9396
Balanced accuracy is: {'val_balanced': 0.685823754789272}
Epoch 26/30
99/99 [==============================] - 32s 321ms/step - loss: 0.1958 - accuracy: 0.9479
Balanced accuracy is: {'val_balanced': 0.8011254789272031}
Epoch 27/30
99/99 [==============================] - 31s 310ms/step - loss: 0.1815 - accuracy: 0.9462
Balanced accuracy is: {'val_balanced': 0.8056752873563218}
Epoch 28/30
99/99 [==============================] - 32s 322ms/step - loss: 0.1984 - accuracy: 0.9398
Balanced accuracy is: {'val_balanced': 0.8251915708812261}
Epoch 29/30
99/99 [==============================] - 32s 323ms/step - loss: 0.1833 - accuracy: 0.9456
Balanced accuracy is: {'val_balanced': 0.831782293377121}
Epoch 30/30
99/99 [==============================] - 31s 313ms/step - loss: 0.1761 - accuracy: 0.9431
Balanced accuracy is: {'val_balanced': 0.7695162835249043}
Evaluating network...
classification report sklearn:
              precision    recall  f1-score   support

       covid       1.00      0.32      0.48       116
   pneumonia       0.83      0.99      0.90        96
     regular       0.85      1.00      0.92       350

    accuracy                           0.86       562
   macro avg       0.89      0.77      0.77       562
weighted avg       0.88      0.86      0.83       562

confusion matrix:
[[ 37  20  59]
 [  0  95   1]
 [  0   0 350]]
Inicio gráfico
cantidad de epocas: 30
Fin gráfico
inicio data
accuracy: [0.6626352667808533, 0.7772119641304016, 0.8128580451011658, 0.8319541811943054, 0.8669637441635132, 0.8695098757743835, 0.8720560073852539, 0.8765117526054382, 0.8975175023078918, 0.911521315574646, 0.9019732475280762, 0.9077020883560181, 0.9140674471855164, 0.9166136384010315, 0.9217059016227722, 0.9191597700119019, 0.9051559567451477, 0.9223424792289734, 0.9280713200569153, 0.9325270652770996, 0.9408020377159119, 0.9344366788864136, 0.9376193284988403, 0.9325270652770996, 0.93507319688797, 0.9490770101547241, 0.9414385557174683, 0.9376193284988403, 0.9471673965454102, 0.9458943605422974]
loss: [0.7782507538795471, 0.5786188244819641, 0.4723375141620636, 0.44739821553230286, 0.3763357400894165, 0.3738308846950531, 0.3509136736392975, 0.3666631579399109, 0.31262215971946716, 0.29183429479599, 0.2852163016796112, 0.28016772866249084, 0.27936917543411255, 0.2413678914308548, 0.2418953776359558, 0.23494404554367065, 0.2837055027484894, 0.23957887291908264, 0.22051097452640533, 0.20856919884681702, 0.19175727665424347, 0.2009083479642868, 0.19531238079071045, 0.20648035407066345, 0.1961812525987625, 0.1868579387664795, 0.18328328430652618, 0.20017699897289276, 0.18582436442375183, 0.17500367760658264]
Traceback (most recent call last):
  File "scripts/train_covid19.py", line 283, in <module>
    print(f'val_accuracy: {val_accuracy}')
NameError: name 'val_accuracy' is not defined
convert the history.history dict to a pandas DataFrame:
No se pudo guardar la data
Traceback (most recent call last):
  File "scripts/train_covid19.py", line 294, in <module>
    hist_df = pd.DataFrame(H.history)
  File "d:\anaconda3\lib\site-packages\pandas\core\frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "d:\anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "d:\anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 78, in arrays_to_mgr
    index = extract_index(arrays)
  File "d:\anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 397, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length
Done, shuttting down!
Done, shuttting down!